package radiostation;

import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class MainForm extends javax.swing.JFrame {
    

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFather = new javax.swing.JPanel();
        jPanelArtistFile = new javax.swing.JPanel();
        jScrollPaneArtists = new javax.swing.JScrollPane();
        jTableArtists = new javax.swing.JTable();
        jButtonInsertArtist = new javax.swing.JButton();
        jButtonChangeArtist = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jPanelAvailableGroups = new javax.swing.JPanel();
        jScrollPaneAvailableGroups = new javax.swing.JScrollPane();
        jTableAvailableGroups = new javax.swing.JTable();
        jButtonInsertGroup = new javax.swing.JButton();
        jButtonEditGroup = new javax.swing.JButton();
        jButtonDeleteGroup = new javax.swing.JButton();
        jPanelAvailableGroupAlbums = new javax.swing.JPanel();
        jScrollPaneAvailableGroups1 = new javax.swing.JScrollPane();
        jTableAvailableGroupAlbums = new javax.swing.JTable();
        jButtonInsertGroupAlbum = new javax.swing.JButton();
        jButtonEditGroupAlbum = new javax.swing.JButton();
        jButtonDeleteGroupAlbum = new javax.swing.JButton();
        jPanelFather2 = new javax.swing.JPanel();
        jPanelArtistManagement = new javax.swing.JPanel();
        jLabelSurName2 = new javax.swing.JLabel();
        jTextFieldSurName2 = new javax.swing.JTextField();
        jLabeName2 = new javax.swing.JLabel();
        jTextFieldName2 = new javax.swing.JTextField();
        jLabelArtisticName2 = new javax.swing.JLabel();
        jTextFieldArtisticName2 = new javax.swing.JTextField();
        jLabelArrtistsex4 = new javax.swing.JLabel();
        jComboBoxsex2 = new javax.swing.JComboBox();
        jLabelArtistDateBirth2 = new javax.swing.JLabel();
        jTextFieldArtistDateBirth2 = new javax.swing.JTextField();
        jLabelArtistBirthPlace2 = new javax.swing.JLabel();
        jTextFieldArtistBirthPlace2 = new javax.swing.JTextField();
        jLabelArrtistsex5 = new javax.swing.JLabel();
        MusicGenre2 = new javax.swing.JComboBox();
        jButtonStoreArtist2 = new javax.swing.JButton();
        jButtonCancelArtistManagement2 = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanelGroupManagement = new javax.swing.JPanel();
        jLabelGroupName = new javax.swing.JLabel();
        jTextFieldGroupName = new javax.swing.JTextField();
        jLabelGroupCreationDate = new javax.swing.JLabel();
        jTextFieldGroupCreationDate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListGroupArtists = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAvailableArtists = new javax.swing.JList();
        jButtonListImportArtist = new javax.swing.JButton();
        jButtonListExportArtist = new javax.swing.JButton();
        jButtonSaveGroup = new javax.swing.JButton();
        jButtonDeleteGr = new javax.swing.JButton();
        jButtonExitGroupManagement = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelGroupAlbumManagement = new javax.swing.JPanel();
        jLabelGroupAlbumTitle = new javax.swing.JLabel();
        jTextFieldGroupAlbumTitle = new javax.swing.JTextField();
        jLabelGroupAlbumType = new javax.swing.JLabel();
        jTextFieldGroupAlbumType = new javax.swing.JTextField();
        jButtonListImportSong = new javax.swing.JButton();
        jButtonListDeleteSong = new javax.swing.JButton();
        jButtonSaveGroupAlbum = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonExitGroupAlbumManagement = new javax.swing.JButton();
        jLabelGroupAlbumNumber = new javax.swing.JLabel();
        jTextFieldGroupAlbumNumber = new javax.swing.JTextField();
        jTextFieldProductionCompany = new javax.swing.JTextField();
        jLabelProductionCompany = new javax.swing.JLabel();
        jLabelBandName = new javax.swing.JLabel();
        jTextFieldBandName = new javax.swing.JTextField();
        jTextFieldDateInMarket = new javax.swing.JTextField();
        jLabelDateInMarket = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListSongs = new javax.swing.JList();
        jButtonExitSecondVersion = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMainMenu = new javax.swing.JMenu();
        jMenuFileManagement = new javax.swing.JMenu();
        jMenuArtists = new javax.swing.JMenuItem();
        jMenuMusicGroup = new javax.swing.JMenuItem();
        jMenuMusicGroupAlboum = new javax.swing.JMenuItem();
        jMenuArtistAlbum = new javax.swing.JMenuItem();
        jMenuSongLists = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ΣΥΣΤΗΜΑ ΡΑΔΙΟΦΩΝΙΚΟΥ ΣΤΑΘΜΟΥ");
        setName("MainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 950));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelFather.setLayout(new java.awt.CardLayout());

        jPanelArtistFile.setBorder(javax.swing.BorderFactory.createTitledBorder("Αρχείο Καλλιτεχνών"));
        jPanelArtistFile.setName("artistFile"); // NOI18N
        jPanelArtistFile.setNextFocusableComponent(jPanelAvailableGroups);

        jTableArtists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneArtists.setViewportView(jTableArtists);

        jButtonInsertArtist.setText("Εισαγωγή");
        jButtonInsertArtist.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonInsertArtist.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonInsertArtist.setName("jButtonInsertArtist"); // NOI18N
        jButtonInsertArtist.setPreferredSize(new java.awt.Dimension(99, 23));
        jButtonInsertArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertArtistActionPerformed(evt);
            }
        });

        jButtonChangeArtist.setText("Μεταβολή");
        jButtonChangeArtist.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonChangeArtist.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonChangeArtist.setName("jButtonChangeArtist"); // NOI18N
        jButtonChangeArtist.setPreferredSize(new java.awt.Dimension(99, 23));
        jButtonChangeArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeArtistActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Διαγραφή");
        jButtonDelete.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonDelete.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonDelete.setPreferredSize(new java.awt.Dimension(99, 23));

        javax.swing.GroupLayout jPanelArtistFileLayout = new javax.swing.GroupLayout(jPanelArtistFile);
        jPanelArtistFile.setLayout(jPanelArtistFileLayout);
        jPanelArtistFileLayout.setHorizontalGroup(
            jPanelArtistFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtistFileLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelArtistFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneArtists, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelArtistFileLayout.createSequentialGroup()
                        .addComponent(jButtonInsertArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jButtonChangeArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanelArtistFileLayout.setVerticalGroup(
            jPanelArtistFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtistFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneArtists, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanelArtistFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChangeArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );

        jPanelFather.add(jPanelArtistFile, "artistFile");
        jPanelArtistFile.getAccessibleContext().setAccessibleParent(jPanelFather);

        jPanelAvailableGroups.setBorder(javax.swing.BorderFactory.createTitledBorder("Αρχείο Διαθέσιμων Συγκροτημάτων"));
        jPanelAvailableGroups.setName("groupFile"); // NOI18N
        jPanelAvailableGroups.setPreferredSize(new java.awt.Dimension(559, 347));

        jTableAvailableGroups.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneAvailableGroups.setViewportView(jTableAvailableGroups);

        jButtonInsertGroup.setText("Εισαγωγή");
        jButtonInsertGroup.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonInsertGroup.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonInsertGroup.setName("jButtonInsertGroup"); // NOI18N
        jButtonInsertGroup.setPreferredSize(new java.awt.Dimension(99, 23));
        jButtonInsertGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertGroupActionPerformed(evt);
            }
        });

        jButtonEditGroup.setText("Μεταβολή");
        jButtonEditGroup.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonEditGroup.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonEditGroup.setName("jButtonEditGroup"); // NOI18N
        jButtonEditGroup.setPreferredSize(new java.awt.Dimension(99, 23));
        jButtonEditGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditGroupActionPerformed(evt);
            }
        });

        jButtonDeleteGroup.setText("Διαγραφή");
        jButtonDeleteGroup.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonDeleteGroup.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonDeleteGroup.setPreferredSize(new java.awt.Dimension(99, 23));

        javax.swing.GroupLayout jPanelAvailableGroupsLayout = new javax.swing.GroupLayout(jPanelAvailableGroups);
        jPanelAvailableGroups.setLayout(jPanelAvailableGroupsLayout);
        jPanelAvailableGroupsLayout.setHorizontalGroup(
            jPanelAvailableGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAvailableGroupsLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPaneAvailableGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAvailableGroupsLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonInsertGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButtonEditGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDeleteGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAvailableGroupsLayout.setVerticalGroup(
            jPanelAvailableGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAvailableGroupsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneAvailableGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(jPanelAvailableGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanelFather.add(jPanelAvailableGroups, "groupFile");
        jPanelAvailableGroups.getAccessibleContext().setAccessibleParent(jPanelFather);

        jPanelAvailableGroupAlbums.setBorder(javax.swing.BorderFactory.createTitledBorder("Αρχείο Διαθέσιμων Άλμπουμ Συγκροτημάτων"));
        jPanelAvailableGroupAlbums.setName("groupAlbumFile"); // NOI18N
        jPanelAvailableGroupAlbums.setPreferredSize(new java.awt.Dimension(559, 347));

        jTableAvailableGroupAlbums.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAvailableGroupAlbums.setName("jTableAvailableGroupAlbums"); // NOI18N
        jScrollPaneAvailableGroups1.setViewportView(jTableAvailableGroupAlbums);

        jButtonInsertGroupAlbum.setText("Εισαγωγή");
        jButtonInsertGroupAlbum.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonInsertGroupAlbum.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonInsertGroupAlbum.setName("jButtonInsertGroupAlbum"); // NOI18N
        jButtonInsertGroupAlbum.setPreferredSize(new java.awt.Dimension(99, 23));
        jButtonInsertGroupAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertGroupAlbumActionPerformed(evt);
            }
        });

        jButtonEditGroupAlbum.setText("Μεταβολή");
        jButtonEditGroupAlbum.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonEditGroupAlbum.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonEditGroupAlbum.setName("jButtonEditGroupAlbum"); // NOI18N
        jButtonEditGroupAlbum.setPreferredSize(new java.awt.Dimension(99, 23));

        jButtonDeleteGroupAlbum.setText("Διαγραφή");
        jButtonDeleteGroupAlbum.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonDeleteGroupAlbum.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonDeleteGroupAlbum.setName("jButtonDeleteGroupAlbum"); // NOI18N
        jButtonDeleteGroupAlbum.setPreferredSize(new java.awt.Dimension(99, 23));

        javax.swing.GroupLayout jPanelAvailableGroupAlbumsLayout = new javax.swing.GroupLayout(jPanelAvailableGroupAlbums);
        jPanelAvailableGroupAlbums.setLayout(jPanelAvailableGroupAlbumsLayout);
        jPanelAvailableGroupAlbumsLayout.setHorizontalGroup(
            jPanelAvailableGroupAlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAvailableGroupAlbumsLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPaneAvailableGroups1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAvailableGroupAlbumsLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonInsertGroupAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButtonEditGroupAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDeleteGroupAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAvailableGroupAlbumsLayout.setVerticalGroup(
            jPanelAvailableGroupAlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAvailableGroupAlbumsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneAvailableGroups1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(jPanelAvailableGroupAlbumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertGroupAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditGroupAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteGroupAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanelFather.add(jPanelAvailableGroupAlbums, "groupAlbumFile");
        jPanelAvailableGroupAlbums.getAccessibleContext().setAccessibleParent(jPanelFather);

        jPanelFather2.setName("jPanelFather2"); // NOI18N
        jPanelFather2.setLayout(new java.awt.CardLayout());

        jPanelArtistManagement.setBorder(javax.swing.BorderFactory.createTitledBorder("Διαχείριση Καλλιτεχνών "));
        jPanelArtistManagement.setName("artistManagement"); // NOI18N

        jLabelSurName2.setText("Επώνυμο");

        jLabeName2.setText("Όνομα");

        jLabelArtisticName2.setText("Καλλιτεχνικό Όνομα");

        jLabelArrtistsex4.setText("Φύλο");

        jComboBoxsex2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3" }));
        jComboBoxsex2.setToolTipText("");
        jComboBoxsex2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxsex2jComboBoxsexActionPerformed(evt);
            }
        });

        jLabelArtistDateBirth2.setText("Ημερομηνία Γέννησης");

        jTextFieldArtistDateBirth2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldArtistDateBirth2jTextFieldArtistDateBirthActionPerformed(evt);
            }
        });

        jLabelArtistBirthPlace2.setText("Τόπος Γέννησης");

        jTextFieldArtistBirthPlace2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldArtistBirthPlace2jTextFieldArtistBirthPlaceActionPerformed(evt);
            }
        });

        jLabelArrtistsex5.setText(" Είδος Μουσικής");

        MusicGenre2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonStoreArtist2.setText("Αποθήκευση");
        jButtonStoreArtist2.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonStoreArtist2.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonStoreArtist2.setPreferredSize(new java.awt.Dimension(99, 23));

        jButtonCancelArtistManagement2.setText("Ακύρωση");
        jButtonCancelArtistManagement2.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonCancelArtistManagement2.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonCancelArtistManagement2.setPreferredSize(new java.awt.Dimension(99, 23));

        jButtonExit.setText("Έξοδος");
        jButtonExit.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonExit.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonExit.setName("jButtonExit"); // NOI18N
        jButtonExit.setPreferredSize(new java.awt.Dimension(99, 23));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitjButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelArtistManagementLayout = new javax.swing.GroupLayout(jPanelArtistManagement);
        jPanelArtistManagement.setLayout(jPanelArtistManagementLayout);
        jPanelArtistManagementLayout.setHorizontalGroup(
            jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtistManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelArtistBirthPlace2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelArrtistsex5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldArtistBirthPlace2)
                    .addComponent(MusicGenre2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanelArtistManagementLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButtonStoreArtist2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jButtonCancelArtistManagement2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanelArtistManagementLayout.createSequentialGroup()
                .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelArtistManagementLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabeName2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSurName2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelArtistManagementLayout.createSequentialGroup()
                                    .addComponent(jLabelArrtistsex4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(26, 26, 26))
                                .addComponent(jLabelArtisticName2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, Short.MAX_VALUE))))
                    .addGroup(jPanelArtistManagementLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelArtistDateBirth2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldArtistDateBirth2)
                    .addComponent(jComboBoxsex2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldName2)
                    .addComponent(jTextFieldArtisticName2)
                    .addComponent(jTextFieldSurName2)))
        );
        jPanelArtistManagementLayout.setVerticalGroup(
            jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtistManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSurName2)
                    .addComponent(jTextFieldSurName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeName2)
                    .addComponent(jTextFieldName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArtisticName2)
                    .addComponent(jTextFieldArtisticName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArrtistsex4)
                    .addComponent(jComboBoxsex2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArtistDateBirth2)
                    .addComponent(jTextFieldArtistDateBirth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldArtistBirthPlace2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelArtistBirthPlace2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MusicGenre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelArrtistsex5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanelArtistManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStoreArtist2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelArtistManagement2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jPanelFather2.add(jPanelArtistManagement, "artistManagement");
        jPanelArtistManagement.getAccessibleContext().setAccessibleParent(jPanelFather2);

        jPanelGroupManagement.setBorder(javax.swing.BorderFactory.createTitledBorder("Διαχείριση Συγκροτημάτων"));
        jPanelGroupManagement.setName("groupManagement"); // NOI18N

        jLabelGroupName.setText("Επωνυμία Συγκροτήματος");

        jLabelGroupCreationDate.setText("Ημερομηνία Δημιουργίας");

        jScrollPane2.setViewportView(jListGroupArtists);

        jScrollPane1.setViewportView(jListAvailableArtists);

        jButtonListImportArtist.setText("Πρόσθεσε >>");

        jButtonListExportArtist.setText("<< Αφαίρεσε");

        jButtonSaveGroup.setText("Αποθήκευση");
        jButtonSaveGroup.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonSaveGroup.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonSaveGroup.setPreferredSize(new java.awt.Dimension(99, 23));

        jButtonDeleteGr.setText("Διαγραφή");
        jButtonDeleteGr.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonDeleteGr.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonDeleteGr.setPreferredSize(new java.awt.Dimension(99, 23));

        jButtonExitGroupManagement.setText("Έξοδoς");
        jButtonExitGroupManagement.setActionCommand("");
        jButtonExitGroupManagement.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonExitGroupManagement.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonExitGroupManagement.setName("jButtonExitGroupManagement"); // NOI18N
        jButtonExitGroupManagement.setPreferredSize(new java.awt.Dimension(99, 23));
        jButtonExitGroupManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitGroupManagementActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 51, 102));
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Λίστα Διαθέσιμων Καλλιτεχνών");

        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("Λίστα Καλλιτεχνών Συγκροτήματος");

        javax.swing.GroupLayout jPanelGroupManagementLayout = new javax.swing.GroupLayout(jPanelGroupManagement);
        jPanelGroupManagement.setLayout(jPanelGroupManagementLayout);
        jPanelGroupManagementLayout.setHorizontalGroup(
            jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGroupManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGroupManagementLayout.createSequentialGroup()
                        .addGroup(jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGroupManagementLayout.createSequentialGroup()
                                .addGroup(jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelGroupName)
                                    .addComponent(jLabelGroupCreationDate))
                                .addGap(32, 32, 32)
                                .addGroup(jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldGroupName)
                                    .addComponent(jTextFieldGroupCreationDate, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                            .addGroup(jPanelGroupManagementLayout.createSequentialGroup()
                                .addGroup(jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSaveGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelGroupManagementLayout.createSequentialGroup()
                                        .addComponent(jButtonDeleteGr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(jButtonExitGroupManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelGroupManagementLayout.createSequentialGroup()
                                        .addGroup(jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonListImportArtist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonListExportArtist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(47, 47, 47)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(97, Short.MAX_VALUE))
                    .addGroup(jPanelGroupManagementLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20))))
        );
        jPanelGroupManagementLayout.setVerticalGroup(
            jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGroupManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGroupName)
                    .addComponent(jTextFieldGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGroupCreationDate)
                    .addComponent(jTextFieldGroupCreationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelGroupManagementLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButtonListImportArtist)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonListExportArtist))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelGroupManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteGr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExitGroupManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jPanelFather2.add(jPanelGroupManagement, "groupManagement");
        jPanelGroupManagement.getAccessibleContext().setAccessibleParent(jPanelFather2);

        jPanelGroupAlbumManagement.setBorder(javax.swing.BorderFactory.createTitledBorder("Διαχείριση Άλμπουμ Συγκροτημάτων"));
        jPanelGroupAlbumManagement.setName("groupAlbumManagement"); // NOI18N

        jLabelGroupAlbumTitle.setText("Τίτλος");
        jLabelGroupAlbumTitle.setName("albumTitle"); // NOI18N

        jTextFieldGroupAlbumTitle.setName("jTextFieldGroupAlbumTitle"); // NOI18N

        jLabelGroupAlbumType.setText("Τύπος Άλμπουμ");
        jLabelGroupAlbumType.setName("jLabelGroupAlbumType"); // NOI18N

        jTextFieldGroupAlbumType.setName("jTextFieldGroupAlbumType"); // NOI18N

        jButtonListImportSong.setText("Εισαγωγή");
        jButtonListImportSong.setName("jButtonListImportSong"); // NOI18N

        jButtonListDeleteSong.setText("Διαγραφή");
        jButtonListDeleteSong.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonListDeleteSong.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonListDeleteSong.setName("jButtonListDeleteSong"); // NOI18N
        jButtonListDeleteSong.setPreferredSize(new java.awt.Dimension(99, 23));

        jButtonSaveGroupAlbum.setText("Αποθήκευση");
        jButtonSaveGroupAlbum.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonSaveGroupAlbum.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonSaveGroupAlbum.setName("jButtonSaveGroupAlbum"); // NOI18N
        jButtonSaveGroupAlbum.setPreferredSize(new java.awt.Dimension(99, 23));

        jButtonCancel.setText("Ακύρωση");
        jButtonCancel.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonCancel.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(99, 23));

        jButtonExitGroupAlbumManagement.setText("Έξοδoς");
        jButtonExitGroupAlbumManagement.setActionCommand("");
        jButtonExitGroupAlbumManagement.setMaximumSize(new java.awt.Dimension(99, 23));
        jButtonExitGroupAlbumManagement.setMinimumSize(new java.awt.Dimension(99, 23));
        jButtonExitGroupAlbumManagement.setName("jButtonExitGroupAlbumManagement"); // NOI18N
        jButtonExitGroupAlbumManagement.setPreferredSize(new java.awt.Dimension(99, 23));
        jButtonExitGroupAlbumManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitGroupAlbumManagementActionPerformed(evt);
            }
        });

        jLabelGroupAlbumNumber.setText("Αριθμός Άλμπουμ");
        jLabelGroupAlbumNumber.setName("jLabelGroupAlbumNumber"); // NOI18N

        jTextFieldGroupAlbumNumber.setName("jTextFieldGroupAlbumNumber"); // NOI18N

        jTextFieldProductionCompany.setName("jTextFieldProductionCompany"); // NOI18N

        jLabelProductionCompany.setText("Εταιρεία Παραγωγής");
        jLabelProductionCompany.setName("jLabelProductionCompany"); // NOI18N

        jLabelBandName.setText("Συγκρότημα");
        jLabelBandName.setName("jLabelBandName"); // NOI18N

        jTextFieldBandName.setName("jTextFieldBandName"); // NOI18N

        jTextFieldDateInMarket.setName("jTextFieldDateInMarket"); // NOI18N

        jLabelDateInMarket.setText("Ημερομηνία Κυκλοφορίας");
        jLabelDateInMarket.setName("jLabelDateInMarket"); // NOI18N

        jListSongs.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListSongs.setName("jListSongs"); // NOI18N
        jScrollPane3.setViewportView(jListSongs);

        javax.swing.GroupLayout jPanelGroupAlbumManagementLayout = new javax.swing.GroupLayout(jPanelGroupAlbumManagement);
        jPanelGroupAlbumManagement.setLayout(jPanelGroupAlbumManagementLayout);
        jPanelGroupAlbumManagementLayout.setHorizontalGroup(
            jPanelGroupAlbumManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGroupAlbumManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGroupAlbumManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelGroupAlbumManagementLayout.createSequentialGroup()
                        .addComponent(jLabelDateInMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jTextFieldDateInMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelGroupAlbumManagementLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(jPanelGroupAlbumManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldGroupAlbumType, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldGroupAlbumNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelGroupAlbumNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGroupAlbumType)
                    .addGroup(jPanelGroupAlbumManagementLayout.createSequentialGroup()
                        .addComponent(jLabelProductionCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jTextFieldProductionCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelGroupAlbumManagementLayout.createSequentialGroup()
                        .addComponent(jLabelBandName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jTextFieldBandName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelGroupAlbumManagementLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButtonListImportSong)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonListDeleteSong, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGroupAlbumManagementLayout.createSequentialGroup()
                        .addComponent(jLabelGroupAlbumTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldGroupAlbumTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelGroupAlbumManagementLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGroupAlbumManagementLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButtonSaveGroupAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jButtonExitGroupAlbumManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelGroupAlbumManagementLayout.setVerticalGroup(
            jPanelGroupAlbumManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGroupAlbumManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGroupAlbumManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGroupAlbumTitle)
                    .addComponent(jTextFieldGroupAlbumTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGroupAlbumManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGroupAlbumType)
                    .addComponent(jTextFieldGroupAlbumType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGroupAlbumManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGroupAlbumNumber)
                    .addComponent(jTextFieldGroupAlbumNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGroupAlbumManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProductionCompany)
                    .addComponent(jTextFieldProductionCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGroupAlbumManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBandName)
                    .addComponent(jTextFieldBandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGroupAlbumManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDateInMarket)
                    .addComponent(jTextFieldDateInMarket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelGroupAlbumManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListImportSong)
                    .addComponent(jButtonListDeleteSong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelGroupAlbumManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExitGroupAlbumManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaveGroupAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanelFather2.add(jPanelGroupAlbumManagement, "groupAlbumManagement");
        jPanelGroupAlbumManagement.getAccessibleContext().setAccessibleParent(jPanelFather2);

        jButtonExitSecondVersion.setText("ΕΞΟΔΟΣ");
        jButtonExitSecondVersion.setName("jButtonExitSecondVersion"); // NOI18N
        jButtonExitSecondVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitSecondVersionActionPerformed(evt);
            }
        });

        jMenuBar.setName("jMenuBar"); // NOI18N

        jMainMenu.setText("ΜΕΝΟΥ");

        jMenuFileManagement.setText("Διαχείριση Αρχείων");

        jMenuArtists.setText("a. Καλλιτέχνες");
        jMenuArtists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArtistsActionPerformed(evt);
            }
        });
        jMenuFileManagement.add(jMenuArtists);

        jMenuMusicGroup.setText("b. Συγκροτήματα");
        jMenuMusicGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMusicGroupActionPerformed(evt);
            }
        });
        jMenuFileManagement.add(jMenuMusicGroup);

        jMenuMusicGroupAlboum.setText("c. Άλμπουμ Συγκροτημάτων");
        jMenuMusicGroupAlboum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMusicGroupAlboumActionPerformed(evt);
            }
        });
        jMenuFileManagement.add(jMenuMusicGroupAlboum);

        jMenuArtistAlbum.setText("d. Άλμπουμ Καλλιτεχνών");
        jMenuFileManagement.add(jMenuArtistAlbum);

        jMainMenu.add(jMenuFileManagement);

        jMenuSongLists.setText("Λίστες Τραγουδιών");
        jMainMenu.add(jMenuSongLists);

        jMenuExit.setText("Έξοδος");
        jMainMenu.add(jMenuExit);

        jMenuBar.add(jMainMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelFather, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelFather2, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jButtonExitSecondVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButtonExitSecondVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelFather2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuArtistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArtistsActionPerformed
        visibilityJPanelFather("artistFile");
    }//GEN-LAST:event_jMenuArtistsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       jPanelFather.setVisible(false);
       jPanelFather2.setVisible(false);
       jButtonExitSecondVersion.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxsex2jComboBoxsexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxsex2jComboBoxsexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxsex2jComboBoxsexActionPerformed

    private void jTextFieldArtistDateBirth2jTextFieldArtistDateBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldArtistDateBirth2jTextFieldArtistDateBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldArtistDateBirth2jTextFieldArtistDateBirthActionPerformed

    private void jTextFieldArtistBirthPlace2jTextFieldArtistBirthPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldArtistBirthPlace2jTextFieldArtistBirthPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldArtistBirthPlace2jTextFieldArtistBirthPlaceActionPerformed

    private void jButtonExitjButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitjButtonExitActionPerformed
        jMenuBar.setVisible(true);
        jPanelFather.setVisible(false);
        jPanelFather2.setVisible(false);
        jButtonExitSecondVersion.setVisible(false);
    }//GEN-LAST:event_jButtonExitjButtonExitActionPerformed

    private void jButtonInsertArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertArtistActionPerformed
        visibilityJPanelFather2("artistManagement");
    }//GEN-LAST:event_jButtonInsertArtistActionPerformed

    private void jButtonChangeArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeArtistActionPerformed
        visibilityJPanelFather2("artistManagement");
    }//GEN-LAST:event_jButtonChangeArtistActionPerformed

    private void jMenuMusicGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMusicGroupActionPerformed
        visibilityJPanelFather("groupFile");
    }//GEN-LAST:event_jMenuMusicGroupActionPerformed

    private void jButtonInsertGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertGroupActionPerformed
        visibilityJPanelFather2("groupManagement");
    }//GEN-LAST:event_jButtonInsertGroupActionPerformed

    private void jButtonEditGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditGroupActionPerformed
        visibilityJPanelFather2("groupManagement"); 
    }//GEN-LAST:event_jButtonEditGroupActionPerformed

    private void jButtonExitGroupManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitGroupManagementActionPerformed
        jMenuBar.setVisible(true);
        jPanelFather.setVisible(false);
        jPanelFather2.setVisible(false);       
        jButtonExitSecondVersion.setVisible(false);
    }//GEN-LAST:event_jButtonExitGroupManagementActionPerformed

    private void jMenuMusicGroupAlboumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMusicGroupAlboumActionPerformed
        visibilityJPanelFather("groupAlbumFile");
    }//GEN-LAST:event_jMenuMusicGroupAlboumActionPerformed

    private void jButtonExitGroupAlbumManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitGroupAlbumManagementActionPerformed
        jMenuBar.setVisible(true);
        jPanelFather.setVisible(false);
        jPanelFather2.setVisible(false);
        jButtonExitSecondVersion.setVisible(false);
    }//GEN-LAST:event_jButtonExitGroupAlbumManagementActionPerformed

    private void jButtonInsertGroupAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertGroupAlbumActionPerformed
        visibilityJPanelFather2("groupAlbumManagement");
    }//GEN-LAST:event_jButtonInsertGroupAlbumActionPerformed

    private void jButtonExitSecondVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitSecondVersionActionPerformed
        jMenuBar.setVisible(true);
        jPanelFather.setVisible(false);
        jPanelFather2.setVisible(false); 
        jButtonExitSecondVersion.setVisible(false); 
    }//GEN-LAST:event_jButtonExitSecondVersionActionPerformed
    private void visibilityJPanelFather(String cardName){
        jPanelFather.setVisible(true);
        CardLayout c2 = (CardLayout) jPanelFather.getLayout();
        c2.show(jPanelFather, cardName);     
        jMenuBar.setVisible(false);
        jButtonExitSecondVersion.setVisible(true); 
}
    private void visibilityJPanelFather2(String cardName){
        jPanelFather2.setVisible(true);
        CardLayout c2 = (CardLayout) jPanelFather2.getLayout();
        c2.show(jPanelFather2, cardName);  
        jMenuBar.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox MusicGenre2;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCancelArtistManagement2;
    private javax.swing.JButton jButtonChangeArtist;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDeleteGr;
    private javax.swing.JButton jButtonDeleteGroup;
    private javax.swing.JButton jButtonDeleteGroupAlbum;
    private javax.swing.JButton jButtonEditGroup;
    private javax.swing.JButton jButtonEditGroupAlbum;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExitGroupAlbumManagement;
    private javax.swing.JButton jButtonExitGroupManagement;
    private javax.swing.JButton jButtonExitSecondVersion;
    private javax.swing.JButton jButtonInsertArtist;
    private javax.swing.JButton jButtonInsertGroup;
    private javax.swing.JButton jButtonInsertGroupAlbum;
    private javax.swing.JButton jButtonListDeleteSong;
    private javax.swing.JButton jButtonListExportArtist;
    private javax.swing.JButton jButtonListImportArtist;
    private javax.swing.JButton jButtonListImportSong;
    private javax.swing.JButton jButtonSaveGroup;
    private javax.swing.JButton jButtonSaveGroupAlbum;
    private javax.swing.JButton jButtonStoreArtist2;
    private javax.swing.JComboBox jComboBoxsex2;
    private javax.swing.JLabel jLabeName2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelArrtistsex4;
    private javax.swing.JLabel jLabelArrtistsex5;
    private javax.swing.JLabel jLabelArtistBirthPlace2;
    private javax.swing.JLabel jLabelArtistDateBirth2;
    private javax.swing.JLabel jLabelArtisticName2;
    private javax.swing.JLabel jLabelBandName;
    private javax.swing.JLabel jLabelDateInMarket;
    private javax.swing.JLabel jLabelGroupAlbumNumber;
    private javax.swing.JLabel jLabelGroupAlbumTitle;
    private javax.swing.JLabel jLabelGroupAlbumType;
    private javax.swing.JLabel jLabelGroupCreationDate;
    private javax.swing.JLabel jLabelGroupName;
    private javax.swing.JLabel jLabelProductionCompany;
    private javax.swing.JLabel jLabelSurName2;
    private javax.swing.JList jListAvailableArtists;
    private javax.swing.JList jListGroupArtists;
    private javax.swing.JList jListSongs;
    private javax.swing.JMenu jMainMenu;
    private javax.swing.JMenuItem jMenuArtistAlbum;
    private javax.swing.JMenuItem jMenuArtists;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuFileManagement;
    private javax.swing.JMenuItem jMenuMusicGroup;
    private javax.swing.JMenuItem jMenuMusicGroupAlboum;
    private javax.swing.JMenuItem jMenuSongLists;
    private javax.swing.JPanel jPanelArtistFile;
    private javax.swing.JPanel jPanelArtistManagement;
    private javax.swing.JPanel jPanelAvailableGroupAlbums;
    private javax.swing.JPanel jPanelAvailableGroups;
    private javax.swing.JPanel jPanelFather;
    private javax.swing.JPanel jPanelFather2;
    private javax.swing.JPanel jPanelGroupAlbumManagement;
    private javax.swing.JPanel jPanelGroupManagement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneArtists;
    private javax.swing.JScrollPane jScrollPaneAvailableGroups;
    private javax.swing.JScrollPane jScrollPaneAvailableGroups1;
    private javax.swing.JTable jTableArtists;
    private javax.swing.JTable jTableAvailableGroupAlbums;
    private javax.swing.JTable jTableAvailableGroups;
    private javax.swing.JTextField jTextFieldArtistBirthPlace2;
    private javax.swing.JTextField jTextFieldArtistDateBirth2;
    private javax.swing.JTextField jTextFieldArtisticName2;
    private javax.swing.JTextField jTextFieldBandName;
    private javax.swing.JTextField jTextFieldDateInMarket;
    private javax.swing.JTextField jTextFieldGroupAlbumNumber;
    private javax.swing.JTextField jTextFieldGroupAlbumTitle;
    private javax.swing.JTextField jTextFieldGroupAlbumType;
    private javax.swing.JTextField jTextFieldGroupCreationDate;
    private javax.swing.JTextField jTextFieldGroupName;
    private javax.swing.JTextField jTextFieldName2;
    private javax.swing.JTextField jTextFieldProductionCompany;
    private javax.swing.JTextField jTextFieldSurName2;
    // End of variables declaration//GEN-END:variables
}
